const actions = {
  DONE_LOADING: 'DONE_LOADING',
  DONE_LOADING_PRODUCT: 'DONE_LOADING_PRODUCT',
  LOADING : 'LOADING',
  LOADING_VALIDATOR: 'LOADING_VALIDATOR',
  LOADING_PRODUCT: 'LOADING_PRODUCT',
  ADD_SCHEDULE_FETCHED: 'ADD_SCHEDULE_FETCHED',
  LIST_OF_WORK_INTENSITY_FETCHED: 'LIST_OF_WORK_INTENSITY_FETCHED',
  LIST_ALL_PROJECT: 'LIST_ALL_PROJECT',
  LIST_SCHEDULE_FETCHED: 'LIST_SCHEDULE_FETCHED',
  LIST_PRODUCT_FECHED: 'LIST_PRODUCT_FECHED',
  LIST_PRODUCT_FETCHED: 'LIST_PRODUCT_FETCHED',
  LIST_NOTIF_FECHED: 'LIST_NOTIF_FECHED',
  LIST_OF_PERSONAL_SCORE_FETCHED: 'LIST_OF_PERSONAL_SCORE_FECHED',
  LIST_OF_SQUAD_BACKLOG: 'LIST_OF_SQUAD_BACKLOG',
  LIST_OF_PERSONAL_BACKLOG: 'LIST_OF_PERSONAL_BACKLOG',
  LIST_TIMELINE_SKILL_FETCHED: 'LIST_TIMELINE_SKILL_FETCHED',
  LIST_PRODUCT_REPORT_FETCHED: 'LIST_PRODUCT_REPORT_FETCHED',
  LIST_OF_SQUAD_PERFORMANCE: 'LIST_OF_SQUAD_PERFORMANCE',
  LIST_OF_TALENT_PERFORMANCE: 'LIST_OF_TALENT_PERFORMANCE',
  VALIDATOR: 'VALIDATOR',
  SQUADDETAIL: 'SQUADDETAIL',
  PERSONALDETAIL: 'PERSONALDETAIL'
};

export default actions;